# Generated by Django 4.0.2 on 2022-03-14 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='sexo',
            field=models.CharField(default=1, max_length=50, verbose_name='Sexo'),
            preserve_default=False,
        ),
    ]
