# Generated by Django 4.0.2 on 2022-03-14 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0002_empleado_sexo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='sexo',
        ),
    ]
