# Generated by Django 4.0.2 on 2022-03-17 20:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0007_category_des_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='fec',
            field=models.DateField(default=datetime.datetime.now, verbose_name='fecha'),
        ),
    ]
